server:
  port: 8882
spring:
  application:
    name: yanwu-file
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yanwu_file?useUnicode=true&characterEncoding=utf8
    username: root
    password: xbf12138
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: 39.97.229.71
    port: 5672
    username: root
    password: xbf12138
  redis:
    host: 39.97.229.71
    port: 6379
    password: xbf12138
    database: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8880/eureka/
logging:
  file: /log/yanwu-file.log
  level:
    com: info
    org: info
    cn: info