package com.yanwu.spring.cloud.common.core.exception;

public interface BusinessExceptionCode {

    int EXCEPTIONCODE_YANWU_BASE = -800000;
    int EXCEPTIONCODE_YANWU_COMMON_BASE = EXCEPTIONCODE_YANWU_BASE - 88000;

    int EXCEPTIONCODE_YANWU_SYS_BASE = EXCEPTIONCODE_YANWU_BASE - 1000;
    int EXCEPTIONCODE_YANWU_CONFIG_BASE = EXCEPTIONCODE_YANWU_BASE - 2000;
    int EXCEPTIONCODE_YANWU_MAINTAIN_BASE = EXCEPTIONCODE_YANWU_BASE - 3000;

    int EXCEPTIONCODE_YANWU_INVENTORY_BASE = EXCEPTIONCODE_YANWU_BASE - 5000;
    int EXCEPTIONCODE_YANWU_ALARM_BASE = EXCEPTIONCODE_YANWU_BASE - 6000;

}
