server:
  port: 8761
spring:
  application:
    name: yanwu-gateway
  redis:
    host: 39.97.229.71
    port: 6379
    password: xbf12138
    timeout: 10000
    database: 1
  cloud:
    gateway:
      routes:
        id: after_routes
        uri: "http://127.0.0.1:8881/*"
        predicates:
          - After=2017-01-20T17:42:47.789-07:00[America/Denver]



eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8880/eureka/

logging:
  file: /log/yanwu-gateway.log
  level:
    com: info
    org: info
    cn: info