server:
  port: 9999
spring:
  application:
    name: yanwu-gateway
  redis:
    host: 39.97.229.71
    port: 6379
    password: xbf12138
    timeout: 10000
    database: 3
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: route_simple
        uri: http://127.0.0.1:9999/api
        predicates:
        - Path=/api/webapp/login/login
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8880/eureka/

logging:
  file: /log/yanwu-gateway.log
  level:
    com: info
    org: info
    cn: info