server:
  port: 8880
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: yanwu-eureka
logging:
  file: /log/yanwu-eureka.log
  level:
    com: info
    org: info
    cn: info