server:
  port: 8883
spring:
  application:
    name: yanwu-netty
  redis:
    host: 39.97.229.71
    port: 6379
    password: xbf12138
    timeout: 10000
    database: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8880/eureka/
logging:
  file: /log/yanwu-netty.log
  level:
    com: info
    org: info
    cn: info
netty:
  port: 6000